import './style.css';
import * as THREE from 'three';
import { createDessert } from './dessert/createDessert.js';
import { setupScene } from './scene/setupScene.js';
import { CONFIG } from './config.js';
import { ClayDeformer } from './deformation/ClayDeformer.js';
import { WaxFractureSystem } from './wax/WaxFractureSystem.js';
import { ClayAssembly } from './deformation/ClayAssembly.js';
import { TactileAudio } from './audio/TactileAudio.js';
import { PointerInteraction } from './interaction/PointerInteraction.js';
const dessert=createDessert();
const app=setupScene(document.querySelector('#scene'),dessert);
app.controls.autoRotate=false;
const meshes=[];dessert.traverse(object=>{if(object.isMesh)meshes.push(object);});
const deformers=new Map();
for(const mesh of meshes) {const config=mesh.name==='puddingMesh'?CONFIG.pudding:mesh.name==='caramelMesh'?CONFIG.caramelClay:mesh.name==='creamMesh'?CONFIG.cream:CONFIG.cherryClay;deformers.set(mesh,new ClayDeformer(mesh,config));}
const wax=new WaxFractureSystem(meshes);
const assembly=new ClayAssembly(deformers,wax),audio=new TactileAudio();
const interaction=new PointerInteraction(app,meshes,wax,deformers,assembly,audio);
const clock=new THREE.Clock();app.controls.saveState();
function resetDessert() {interaction.reset();assembly.reset();audio.stop();for(const d of deformers.values())d.reset();wax.reset();app.controls.reset();app.controls.autoRotate=false;}
document.querySelector('#knead').addEventListener('click',()=>{interaction.release();audio.unlock();if(wax.removed.some(v=>v===0))audio.crack();assembly.knead();});
document.querySelector('#sound').addEventListener('click',e=>{audio.setEnabled(!audio.enabled);e.currentTarget.setAttribute('aria-pressed',String(audio.enabled));e.currentTarget.textContent=audio.enabled?'音效：开':'音效：关';});
document.querySelector('#reset').addEventListener('click',resetDessert);
document.querySelector('#thickness').addEventListener('input',e=>{wax.setThickness(Number(e.target.value));document.querySelector('#thickness-value').value=Number(e.target.value).toFixed(2);});
document.querySelector('#pudding-softness').addEventListener('input',e=>{CONFIG.pudding.softness=Number(e.target.value);});
document.querySelector('#cream-softness').addEventListener('input',e=>{CONFIG.cream.softness=Number(e.target.value);});
document.querySelector('#plasticity').addEventListener('input',e=>{CONFIG.pudding.plasticity=Number(e.target.value);CONFIG.cream.plasticity=Math.min(.98,CONFIG.pudding.plasticity+.07);});
app.renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.035);interaction.update(dt);if(assembly.update(dt))audio.clay(.8);for(const deformer of deformers.values())deformer.update(dt);wax.update(dt);app.controls.update();app.renderer.render(app.scene,app.camera);});
window.pudding={...app,dessert,wax,deformers,interaction,assembly,audio,resetDessert,CONFIG};
